- cookiecutter.json
> TEL-1866: add cookiecutter.json

- {{cookiecutter.docker_name_formatted}}/Makefile
> TEL-1866: remove call to unittest, not implemented yet

- {{cookiecutter.docker_name_formatted}}/.bandit
> TEL-1866: add .bandit config file

- {{cookiecutter.docker_name_formatted}}/Makefile
> TEL-1866: remove black

- cookiecutter.json
- {{cookiecutter.docker_name_formatted}}/Makefile
- {{cookiecutter.docker_name_formatted}}/bin/docker-tools.sh
- {{cookiecutter.docker_name_formatted}}/buildspec.yml
> TEL-1866: add buildspec.yml and allow docker-tools.sh to build and deploy images

- {{cookiecutter.docker_name_formatted}}/buildspec.yml
> TEL-1866: remove empty env section in buildspec.yml

- {{cookiecutter.docker_name_formatted}}/bin/docker-tools.sh
> TEL-1866: export version before running package

- {{cookiecutter.docker_name_formatted}}/bin/docker-tools.sh
> TEL-1866: add publish_to_ecr function

- cookiecutter.json
- {{cookiecutter.docker_name_formatted}}/bin/docker-tools.sh
What did we do?
--
1. Parameterised build args to allow additional docker build info to be added in json
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-1866
Evidence of work
--
1. N/A
Next Steps
--
1. N/A
Risks
--
1. N/A
Collaboration
--
Co-authored-by: Lee Myring <29373851+thinkstack@users.noreply.github.com>
> TEL-1866 parameterise build args in docker-tools script

- cookiecutter.json
- {{cookiecutter.docker_name_formatted}}/bin/docker-tools.sh
* see https://cookiecutter.readthedocs.io/en/2.1.1/advanced/dict_variables.html for details
> TEL-1866: change list into dictionary

- {{cookiecutter.docker_name_formatted}}/bin/docker-tools.sh
> TEL-1866: fix missing double quotes

- {{cookiecutter.docker_name_formatted}}/bin/docker-tools.sh
> TEL-1866: fix missing whitespace

- {{cookiecutter.docker_name_formatted}}/bin/docker-tools.sh
> TEL-1866: fix docker argument name typo

- {{cookiecutter.docker_name_formatted}}/.tool-versions
What did we do?
--
1.
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-
Evidence of work
--
1.
Next Steps
--
1.
Risks
--
1.
Collaboration
--
Co-authored-by:
> TEL-1866: fix end of file line break and trailing spaces

- {{cookiecutter.docker_name_formatted}}/.dockerignore
- {{cookiecutter.docker_name_formatted}}/.pre-commit-config.yaml
> TEL-1866: add pre-commit check for tool versions

- cookiecutter.json
- {{cookiecutter.docker_name_formatted}}/bin/docker-tools.sh
> TEL-1866: split default and additional build info dictionaries

- README.md
> TEL-1866: update README to demonstrate different build parameters

- cookiecutter.json
> TEL-1866: fix typo

- cookiecutter.json
> TEL-1866: add default for default build options

- README.md
- cookiecutter.json
- {{cookiecutter.docker_image_name_formatted}}/bin/docker-tools.sh
> TEL-1866: jinja boolean comparisons don't work as expected in cruft

- {{cookiecutter.docker_image_name_formatted}}/Makefile
- {{cookiecutter.docker_image_name_formatted}}/bin/docker-tools.sh
- {{cookiecutter.docker_image_name_formatted}}/buildspec.yml
- {{cookiecutter.docker_image_name_formatted}}/buildspec_pr.yml
- {{cookiecutter.docker_image_name_formatted}}/tools/check-tool-versions.sh
> TEL-1866: add comment to indicate these files are templates and not to be edited in-situ

- README.md
> TEL-1866: don't use elastic-loadtest as an example

- README.md
What did we do?
--
1. Update README to make the existing repo instructions a bit clearer for simpletons like me.
> Update existing repo instructions for clarity

- {{cookiecutter.docker_image_name_formatted}}/Makefile
Co-authored-by: Ali Bahman <1422984+webit4me@users.noreply.github.com>
> TEL-3955 add MAKE task to update cruft

- {{cookiecutter.docker_image_name_formatted}}/Makefile
Co-authored-by: Ali Bahman <1422984+webit4me@users.noreply.github.com>
> TEL-3955 make cruft update task betterer

- cookiecutter.json
- {{cookiecutter.docker_image_name_formatted}}/Makefile
Co-authored-by: Ali Bahman <1422984+webit4me@users.noreply.github.com>
> TEL-3955 stop using defaults in cookiecutter.json

- {{cookiecutter.docker_image_name_formatted}}/Makefile
Co-authored-by: Ali Bahman <1422984+webit4me@users.noreply.github.com>
> TEL-3955 remove the poetry experimental flag

- README.md
What did we do?
--
1. Add a link to Cookiecutter attributes
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4102
Evidence of work
--
1.
Next Steps
--
1.
Risks
--
1.
Collaboration
--
Co-authored-by: Rob White <Crumplepang@users.noreply.github.com>
> TEL-4102 Add link to Cookiecutter attributes

- {{cookiecutter.docker_image_name_formatted}}/buildspec_pr.yml
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4189
Collaboration
--
Co-authored by: Stephen Palfreyman <18111914+sjpalf@users.noreply.github.com>
> TEL-4189 Updates buildspec to use the right pip
